# Generated by Django 4.0.6 on 2022-07-14 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
